version: '3'

services:
  # api:
  db:
    image: postgres:15.1-alpine3.17
    restart: always
    environment:
      POSTGRES_DB: myDataBase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  cache:
    image: redis:7.0.8-alpine3.17
    restart: always
    ports:
      - 6379:6379